package com.project.pethost.controller;

import com.project.pethost.converter.GenderEnumConverter;
import com.project.pethost.exception.EmailExistsException;
import com.project.pethost.model.Gender;
import com.project.pethost.model.Person;
import com.project.pethost.repository.PersonRepository;
import com.project.pethost.repository.PetRepository;
import com.project.pethost.service.PersonService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.support.FormattingConversionService;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport;

import java.time.LocalDate;
import java.util.List;

@Controller
@RequestMapping(path = "/pethost")
public class MainController extends WebMvcConfigurationSupport {
    private static final Logger LOGGER = LoggerFactory.getLogger(MainController.class);

    @Autowired // This means to get the bean called personRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PersonRepository personRepository;
    @Autowired
    private PetRepository petRepository;

    @Autowired
    private PersonService personService;


    @GetMapping(path = "/register") // Map ONLY GET Requests
    public @ResponseBody String addNewPerson(@RequestParam final String name,
                                             @RequestParam final String surname,
                                             @RequestParam(required = false) final String patronymic,
                                             @RequestParam(name = "gender") Gender gender,

                                             @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
                                             @RequestParam(required = false) final LocalDate birthdate,

                                             @RequestParam final String email,
                                             @RequestParam(required = false) final List<String> phone,
                                             @RequestParam(required = false) final Long districtId,
                                             @RequestParam(required = false) final Long cityId,
                                             @RequestParam(required = false) final String address,
                                             @RequestParam final String password,
                                             @RequestParam final String matchingPassword
                                             //@ModelAttribute final List<AnimalCategory> animalCategories
                                            ) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request


        final Person p = new Person();
        p.setName(name);
        p.setSurname(surname);
        p.setPatronymic(patronymic);
        p.setGender(gender);
        p.setBirthdate(birthdate);
        p.setEmail(email);
        p.setPhone(phone);
        p.setPassword(password);
        p.setMatchingPassword(matchingPassword);
        //p.setDistrict();
        //p.setCityId();
        p.setAddress(address);
        //personRepository.save(p);
        try {
            personService.registerNewUserAccount(p);
        } catch (EmailExistsException e) {
            e.printStackTrace();
        }
        return "Saved";
    }

    @RequestMapping(value = "/login", method = RequestMethod.GET)
    public String login(final Model model, final String error, final String logout) {
        if (error != null)
            model.addAttribute("error", "Your username and password is invalid.");

        if (logout != null)
            model.addAttribute("message", "You have been logged out successfully.");

        return "login";
    }

    @Override
    public FormattingConversionService mvcConversionService() {
        FormattingConversionService f = super.mvcConversionService();
        f.addConverter(new GenderEnumConverter());
        return f;
    }

    /*@GetMapping(path = "/createPet") // Map ONLY GET Requests
    public @ResponseBody String addNewPet(@RequestParam String name, @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        final Pet n = new Pet();
        n.setName(name);
        n.setBirthdate(birthdate);
        petRepository.save(n);
        return "Saved";
    }
*/
    @GetMapping(path = "/allUsers")
    public @ResponseBody Iterable<Person> getAllUsers() {
        // This returns a JSON or XML with the users
        return personRepository.findAll();
    }

    /*
        /allUsers

        /showAllOrders

        /showAllWaitingOrders

        /searchWaitingPetsByCategories

        /searchPersonsByInterests

        /registerUser(create new Person)

        /logIn

        /createPet

        !!!
        /authorization(for order)
        login
        password

        /sendOrder

        /changeOrderStatus

        /createReview(only by ownerId about keeperId)

        /recalculateRating

        /error
     */
}

